### ISSUE TITLE
Hello, there was no 'index.html'

### ISSUE THREAD

**Issue by jonirrings** [sayden/graphql-mongodb-example#3]
no index.html found, and when browse "_localhost:9000_",  got a '_cannot /get_'.
THANK YOU, the code is useful for my relay-grahpql-mongodb study

**Comment by sayden** [comment]
Hi @jonirrings The GraphQL example is just the server to make POST request against. If you want a full UI example you can check this using Relay https://github.com/sayden/relay-mongoose-example.

Also, source code has in `server.es6` pointed wrongly to an `index.html` that in fact, as you pointed out, didn't exists.

It is corrected already.

Thank you very much
